"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent


# Seguridad
SECRET_KEY = 'django-insecure-i@+zl&*sdkooyavt2*szc&lfy(dl7j8khgp5=b!d)2s#8j!s#g'

DEBUG = True

ALLOWED_HOSTS = []



# Aplicaciones

INSTALLED_APPS = [

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',


    # Instaladas

    'rest_framework',

    'corsheaders',

    'users',

]



# Middleware

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',


    # CORS para React

    'corsheaders.middleware.CorsMiddleware',


    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]



ROOT_URLCONF = 'backend.urls'



# IMPORTANTE PARA DJANGO ADMIN

TEMPLATES = [

    {

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]



WSGI_APPLICATION = 'backend.wsgi.application'

ASGI_APPLICATION = 'backend.asgi.application'



# Base de datos

DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.sqlite3',

        'NAME': BASE_DIR / 'db.sqlite3',

    }

}



# Validadores contraseña

AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]



# Usuario personalizado

AUTH_USER_MODEL = 'users.CustomUser'



# Idioma

LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'UTC'


USE_I18N = True


USE_TZ = True



# Archivos estáticos

STATIC_URL = 'static/'



# Django REST Framework + JWT

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (

        'rest_framework_simplejwt.authentication.JWTAuthentication',

    ),

}



# CORS React

CORS_ALLOWED_ORIGINS = [

    'http://localhost:3000',

    'http://127.0.0.1:3000',

]


CORS_ALLOW_CREDENTIALS = True